# Generated by Django 3.2 on 2022-03-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_complete',
            new_name='is_done',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
